name: instant_gram
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.1.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  uuid: ^3.0.7
  font_awesome_flutter: ^10.3.0
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^5.4.3
  image_picker: ^0.8.6
  image: ^4.0.10
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  intl: ^0.17.0
  video_thumbnail: ^0.5.3
  video_player: ^2.4.10
  lottie: ^2.2.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true