// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjNuQtHV8dGpjApkw4OW7qSwDcfP_pkE',
    appId: '1:844604162281:web:2186661f0743e56b27b078',
    messagingSenderId: '844604162281',
    projectId: 'ahmadinstagram',
    authDomain: 'ahmadinstagram.firebaseapp.com',
    storageBucket: 'ahmadinstagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGw-UoPd842RsG1AZ0EbjLSHDip6VKAww',
    appId: '1:844604162281:android:291e1ae12d932edd27b078',
    messagingSenderId: '844604162281',
    projectId: 'ahmadinstagram',
    storageBucket: 'ahmadinstagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0PkrczE5SC_f6s4uofbourxDuG4R6Xc',
    appId: '1:844604162281:ios:9aaf6c0b2228f4b927b078',
    messagingSenderId: '844604162281',
    projectId: 'ahmadinstagram',
    storageBucket: 'ahmadinstagram.appspot.com',
    iosClientId: '844604162281-421vpilsttrag4olup8q4p5maqdhpcs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0PkrczE5SC_f6s4uofbourxDuG4R6Xc',
    appId: '1:844604162281:ios:9aaf6c0b2228f4b927b078',
    messagingSenderId: '844604162281',
    projectId: 'ahmadinstagram',
    storageBucket: 'ahmadinstagram.appspot.com',
    iosClientId: '844604162281-421vpilsttrag4olup8q4p5maqdhpcs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantGram',
  );
}
